version: '3'

services: 
  redis:
    image: "redis:alpine"
    environment: 
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_USER: michaelchan
  imagegallery:
    build: .
    depends_on:
      - redis
    ports:
      - '3001:3001'
    command: ["npm", "start"]